version: '3'
services:
        web:
                image: all-in-one
                build: .
                ports:
                        - "8794:8086"
                volumes:
                        - ./volumes:/volumes
                        - ./instance:/instance
                restart: unless-stopped
